insert into CATEGORY VALUES(1,'CAT1','ELECTRONIQUE' );
insert into CATEGORY VALUES(2,'CAT2','MEUBLE');

insert into PRODUCT VALUES(1,'ORDINATEUR','PROD1',1);
insert into PRODUCT VALUES(2,'CELLULAIRE','PROD2',1);
insert into PRODUCT VALUES(3,'TABLETTE','PROD3',1);

insert into PRODUCT VALUES(4,'CHAISE','PROD4',2);
insert into PRODUCT VALUES(5,'ARMOIRE','PROD5',2);
insert into PRODUCT VALUES(6,'TABLE','PROD6',2);